# CTI-110
# P4T1b_johnsonelizabeth
# Elizabeth Johnson
# 10/1/19

# No inputs needed from user
# No calculations needed
# Code for turtle to write my initals, EJ


import turtle
turtle.pensize('2')
turtle.pencolor('SeaGreen2')
turtle.fillcolor('SeaGreen2')
turtle.bgcolor('lavender')
turtle.penup()
turtle.backward(160)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.forward(150)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
turtle.penup()
turtle.right(180)
turtle.forward(140)
turtle.pendown()
turtle.begin_fill()
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(110)
turtle.end_fill()
